//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientId { get; set; }
        public string Name { get; set; }
        public string CardNo { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
    }
}
